<?php
/**
 * Help content for schedules
 *
 * PHP Version: 7.3
 *
 * @category Faculty,_Weekly,_Schedule
 * @package  FacultyWeeklySchedule
 * @author   George Cooke <profgeorgecooke@gmail.com>
 * @license  GPL-2.0-or-later https://www.gnu.org/licenses/gpl-2.0.html
 * @link     https://wordpress.org/plugins/faculty-weekly-schedule
 */

// disable direct file access.
if ( ! defined( 'ABSPATH' ) ) {
	exit( 1 );
}

$help_schedule  = '';
$help_schedule .= '<h3>' . __( 'Overview', 'faculty-weekly-schedule' ) . '</h3>';
$help_schedule .= '<p>' . __( 'The Add new Schedule option allows for adding a schedule to be viewed. An unlimited number of schedules can be added. For each new schedule, enter the desired information as shown below.', 'faculty-weekly-schedule' ) . '</p>';
$help_schedule .= '</p>';
$help_schedule .= '<nav class="fws-nav-help">';
$help_schedule .= '<ul>';
$help_schedule .= '<li style="display: inline-block;">';
$help_schedule .= '<a href="#schedule-information">' . __( 'Schedule Information', 'faculty-weekly-schedule' ) . '</a>';
$help_schedule .= '</li>';
$help_schedule .= '<li style="display: inline-block;">';
$help_schedule .= '&nbsp;|&nbsp;<a href="#office-hours">' . __( 'Office Hours Information', 'faculty-weekly-schedule' ) . '</a>';
$help_schedule .= '</li>';
$help_schedule .= '<li style="display: inline-block;">';
$help_schedule .= '&nbsp;|&nbsp;<a href="#classes">' . __( 'Classes Information', 'faculty-weekly-schedule' ) . '</a>';
$help_schedule .= '</li>';
$help_schedule .= '<li style="display: inline-block;">';
$help_schedule .= '&nbsp;|&nbsp;<a href="#options">' . __( 'Schedule Options', 'faculty-weekly-schedule' ) . '</a>';
$help_schedule .= '</li>';
$help_schedule .= '<li style="display: inline-block;">';
$help_schedule .= '&nbsp;|&nbsp;<a href="#headings">' . __( 'Heading Options', 'faculty-weekly-schedule' ) . '</a>';
$help_schedule .= '</li>';
$help_schedule .= '<li style="display: inline-block;">';
$help_schedule .= '&nbsp;|&nbsp;<a href="#messages">' . __( 'Schedule Messages', 'faculty-weekly-schedule' ) . '</a>';
$help_schedule .= '</li>';
$help_schedule .= '</ul>';
$help_schedule .= '</nav>';

// Faculty Information.
$help_schedule .= '<h3 id="schedule-information">' . __( 'Schedule Information', 'faculty-weekly-schedule' ) . '</h3>';
$help_schedule .= '<p>' . __( 'The Schedule Information section allows setting the values relating to the schedule and faculty whenever a schedule is viewed.', 'faculty-weekly-schedule' ) . '.</p>';
$help_schedule .= '<p>' . __( 'The', 'faculty-weekly-schedule' ) . ' <a href ="' . site_url() . '/wp-admin/admin.php?page=fws_settings_page&tab=fws_faculty_tab">' . __( 'Faculty Settings', 'faculty-weekly-schedule' ) . '</a> ' . __( 'tab allows setting the default values relating to faculty whenever a new schedule is added.', 'faculty-weekly-schedule' ) . '.</p>';
$help_schedule .= '<p><img src="' . esc_url( plugins_url( 'schedule/schedule-information.jpeg', __FILE__ ) ) . '" alt="' . __( 'Schedule Information', 'faculty-weekly-schedule' ) . '" /></p>';
$help_schedule .= '<h4>' . __( 'Start Date', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The start date for a schedule is displayed when the <strong>Show Schedule Heading</strong> option is checked. See the <em>Schedule Headings Defaults</em> panel. If the start date is not specified, then no start date will be displayed.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'End Date', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The end date for a schedule is displayed when the <strong>Show Schedule Heading</strong> option is checked. See the <em>Schedule Headings Defaults</em> panel. If the end date is not specified, then no end date will be displayed.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Start Time', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The start time for a schedule is displayed when the <strong>Include Schedule Times</strong> option is checked. See the <em>Schedule Headings Defaults</em> panel. If the start time has been set in the <em>Faculty</em> settings tab, then that start time is defaulted and can be overridden for each individual schedule.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'End Time', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The end time for a schedule is displayed when the <strong>Include Schedule Times</strong> option is checked. See the <em>Schedule Headings Defaults</em> panel. If the end time has been set in the <em>Faculty</em> settings tab, then that end time is defaulted and can be overridden for each individual schedule.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Name', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The name of the faculty member for a schedule is displayed when the <strong>Show Name</strong> option is checked. See the <em>Schedule Options</em> panel. If the name has been set in the <em>Faculty</em> settings tab, then that name is defaulted and can be overridden for each individual schedule.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Title', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The title of the faculty member for a schedule is displayed when the <strong>Show Title</strong> option is checked. See the <em>Schedule Options</em> panel. If the title has been set in the <em>Faculty</em> settings tab, then that title is defaulted and can be overridden for each individual schedule.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Photograph', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The photograph of the faculty member for a schedule is displayed when the <strong>Show Photograph</strong> option is checked. See the <em>Schedule Options</em> panel. If the photograph has been set in the <em>Faculty</em> settings tab, then that photograph is defaulted and can be overridden for each individual schedule.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';

// Office Hours Information.
$help_schedule .= '<h3 id="office-hours">' . __( 'Office Hours Information', 'faculty-weekly-schedule' ) . '</h3>';
$help_schedule .= '<p>' . __( 'The Office Hours Information section allows setting the values relating to office hours blocks whenever a schedule is viewed. An unlimited number of office hours blocks can be added using the + button and when more than one office hours block has been added, the - button can be used to delete an office hours block. If multiple office hours blocks are added, they can be sorted using drag and drop. Sorting is not required for viewing a schedule as office hours blocks are sorted in time and date sequence within selected days of the week. If no day of the week is selected, then the office hours block will not be displayed in the schedule.', 'faculty-weekly-schedule' ) . '.</p>';
$help_schedule .= '<p>' . __( 'The', 'faculty-weekly-schedule' ) . ' <a href ="' . site_url() . '/wp-admin/admin.php?page=fws_settings_page&tab=fws_office_hours_tab">' . __( 'Office Hours Settings', 'faculty-weekly-schedule' ) . '</a> ' . __( 'tab allows setting the default values relating to the first office hours block whenever a new schedule is added.', 'faculty-weekly-schedule' ) . '.</p>';
$help_schedule .= '<p><img src="' . esc_url( plugins_url( 'schedule/office-hours.jpeg', __FILE__ ) ) . '" alt="' . __( 'Office Hours Information', 'faculty-weekly-schedule' ) . '" /></p>';
$help_schedule .= '<h4>' . __( 'Start Time', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The start time for an office hours block. If the start time has been set in the <em>Office Hours</em> settings tab, then that start time is defaulted and can be overridden for the first office hours block. Subsequent office hours blocks will default to the start time from the already added block.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'End Time', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The end time for an office hours block. If the end time has been set in the <em>Office Hours</em> settings tab, then that end time is defaulted and can be overridden for the first office hours block. Subsequent office hours blocks will default to the end time from the already added block.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Start Date', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The start date for an office hours block. If no start date is entered, then the date line in the schedule for the office hours block will be omitted.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'End Date', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The end date for an office hours block. If no end date is entered, then the date line in the schedule for the office block will be omitted.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Block Title', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The title for an office hours block. If the title has been set in the <em>Office Hours</em> settings tab, then that title is defaulted and can be overridden for the first office hours block. Subsequent office hours blocks will have an empty block title field. If the title is not entered, then the title line in the schedule for the office hours block will be omitted.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Campus', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The campus for an office hours block. If the campus has been set in the <em>Office Hours</em> settings tab, then that campus is defaulted and can be overridden for the first office hours block. Subsequent office hours blocks will have an empty campus field. If the campus is not entered, then the campus/location line in the schedule for the office hours block will be omitted.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Location', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The location for an office hours block. If the location has been set in the <em>Office Hours</em> settings tab, then that location is defaulted and can be overridden for the first office hours block. Subsequent office hours blocks will have an empty location field. If the location is not entered, then the campus/location line in the schedule for the office hours block will be omitted.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Office Hours Background Color', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The background color for an office hours block. If the background color has been set in the <em>Office Hours</em> settings tab, then that background color is defaulted and can be overridden for the first office hours block and subsequent office hours blocks. If the background color is not entered, then the background color of the active theme is used. If there are different block titles in a schedule it is recommended that different background and text colors be selected for each block title to make them stand out when viewing the schedule.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Office Hours Text Color', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The text color for an office hours block. If the text color has been set in the <em>Office Hours</em> settings tab, then that text color is defaulted and can be overridden for the first office hours block and subsequent office hours blocks. If the text color is not entered, then the text color of the active theme is used.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Day of Week', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The days of the week for an office hours block. Multiple days of the week for an office hours block can be selected by holding down the Ctrl/Cmd key while selecting a day. If no day of the week is selected, the entire office hours block is omitted when viewing the schedule.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';

// Classes Information.
$help_schedule .= '<h3 id="classes">' . __( 'Classes Information', 'faculty-weekly-schedule' ) . '</h3>';
$help_schedule .= '<p>' . __( 'The Classes Information section allows setting the values relating to classes blocks whenever a schedule is viewed. An unlimited number of class blocks can be added using the + button and when more than one class block has been added, the - button can be used to delete a class block. If multiple class blocks are added, they can be sorted using drag and drop. Sorting is not required as class blocks are sorted in time and date sequence within selected days of the week. If no day of the week is selected, then the class block will not be displayed in the schedule.', 'faculty-weekly-schedule' ) . '.</p>';
$help_schedule .= '<p>' . __( 'The', 'faculty-weekly-schedule' ) . ' <a href ="' . site_url() . '/wp-admin/admin.php?page=fws_settings_page&tab=fws_classes_tab">' . __( 'Classes Settings', 'faculty-weekly-schedule' ) . '</a> ' . __( 'tab allows setting the default values relating to the first class whenever a new schedule is added.', 'faculty-weekly-schedule' ) . '.</p>';
$help_schedule .= '<p><img src="' . esc_url( plugins_url( 'schedule/classes.jpeg', __FILE__ ) ) . '" alt="' . __( 'Classes Information', 'faculty-weekly-schedule' ) . '" /></p>';
$help_schedule .= '<h4>' . __( 'Start Time', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The start time for a class block. If the start time has been set in the <em>Class</em> settings tab, then that start time is defaulted and can be overridden for the first class block. Subsequent class blocks will default to the start time from the already added block.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'End Time', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The end time for a class block. If the end time has been set in the <em>Class</em> settings tab, then that end time is defaulted and can be overridden for the first class block. Subsequent class blocks will default to the end time from the already added block.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Start Date', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The start date for a class block. If no start date is entered, then the date line in the schedule for the class block will be omitted.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'End Date', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The end date for a class block. If no end date is entered, then the date line in the schedule for the office block will be omitted.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Course Number/Name', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The course number/name for a class block. If the course number/name is not entered, then the course number/name line in the schedule for the class block will be omitted.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Course Title', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The course title for a class block. If the course title is not entered, then the course title line in the schedule for the class block will be omitted.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Reference/Section Number', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The reference/section number for a class block. If the reference/section number is not entered, then the reference/section number line in the schedule for the class block will be omitted.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Campus', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The campus for a class block. If the campus has been set in the <em>Class</em> settings tab, then that campus is defaulted and can be overridden for the first class block. Subsequent class blocks will have an empty campus field. If the campus is not entered, then the campus/location line in the schedule for the class block will be omitted.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Location', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The location for a class block. If the location has been set in the <em>Class</em> settings tab, then that location is defaulted and can be overridden for the first class block. Subsequent class blocks will have an empty location field. If the location is not entered, then the campus/location line in the schedule for the class block will be omitted.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Online Class', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'Check <strong>Yes</strong> if the class is a fully online class that has no meetings at a location. Online classes are shown in a separate section of the schedule. If Yes is checked, the start/end time, campus, location and class days values are ignored.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Class Background Color', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The background color for a class block. If the background color has been set in the <em>Class</em> settings tab, then that background color is defaulted and can be overridden for the first class block and subsequent class blocks. If the background color is not entered, then the background color of the active theme is used. It is recommended that different background and text colors be selected for each class to make them stand out when viewing the schedule.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Class Text Color', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The text color for a class block. If the text color has been set in the <em>Class</em> settings tab, then that text color is defaulted and can be overridden for the first class block and subsequent class blocks. If the text color is not entered, then the text color of the active theme is used.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Class Days', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The class days for a class block. Multiple class days for a class block can be selected by holding down the Ctrl/Cmd key while selecting a day. If no class day is selected, the entire class block is omitted when viewing the schedule.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';

// Schedule Options.
$help_schedule .= '<h3 id="options">' . __( 'Schedule Options', 'faculty-weekly-schedule' ) . '</h3>';
$help_schedule .= '<p>' . __( 'The', 'faculty-weekly-schedule' ) . ' <a href ="' . site_url() . '/wp-admin/edit.php?post_type=fws-schedule&page=faculty_weekly_schedule_settings#fws_options">' . __( 'Options Settings', 'faculty-weekly-schedule' ) . '</a> ' . __( 'tab allows setting the default values relating to options whenever a new schedule is added.', 'faculty-weekly-schedule' ) . '.</p>';
$help_schedule .= '<p><img src="' . esc_url( plugins_url( 'schedule/schedule-options.jpeg', __FILE__ ) ) . '" alt="' . __( 'Schedule Options', 'faculty-weekly-schedule' ) . '" /></p>';
$help_schedule .= '<h4>' . __( 'Display Options', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<ul style="margin-left: 3em;">';
$help_schedule .= '<li style="list-style: disc;">';
$help_schedule .= '<strong>' . __( 'Show Name', 'faculty-weekly-schedule' ) . '</strong> - ' . __( 'Will show the name of the faculty at the top of the schedule', 'faculty-weekly-schedule' );
$help_schedule .= '</li>';
$help_schedule .= '<li style="list-style: disc;">';
$help_schedule .= '<strong>' . __( 'Show Title', 'faculty-weekly-schedule' ) . '</strong> - ' . __( 'Will show the title of the faculty at the top of the schedule', 'faculty-weekly-schedule' );
$help_schedule .= '</li>';
$help_schedule .= '<li style="list-style: disc;">';
$help_schedule .= '<strong>' . __( 'Use Title Colors', 'faculty-weekly-schedule' ) . '</strong> - ' . __( 'Will use the background and text colors below (if set) for the name and title if Show Name or Show Title are checked', 'faculty-weekly-schedule' );
$help_schedule .= '</li>';
$help_schedule .= '<li style="list-style: disc;">';
$help_schedule .= '<strong>' . __( 'Use Padding', 'faculty-weekly-schedule' ) . '</strong> - ' . __( 'Will use the padding below for the schedule and blocks containing columns', 'faculty-weekly-schedule' );
$help_schedule .= '</li>';
$help_schedule .= '<li style="list-style: disc;">';
$help_schedule .= '<strong>' . __( 'Use Column Gap', 'faculty-weekly-schedule' ) . '</strong> - ' . __( 'Will use the column gap below for the size of the gap, horizontally and vertically, between blocks', 'faculty-weekly-schedule' );
$help_schedule .= '</li>';
$help_schedule .= '<li style="list-style: disc;">';
$help_schedule .= '<strong>' . __( 'Break Long Lines', 'faculty-weekly-schedule' ) . '</strong> - ' . __( 'Will break long lines in a block that tend to automatically wrap the more days of the week that has office hours and/or classes. Dates, times and location lines are affected.', 'faculty-weekly-schedule' );
$help_schedule .= '</li>';
$help_schedule .= '<li style="list-style: disc;">';
$help_schedule .= '<strong>' . __( 'Use Schedule Background Colors', 'faculty-weekly-schedule' ) . '</strong> - ' . __( 'Will use the background and text colors below (if set) for the entire schedule', 'faculty-weekly-schedule' );
$help_schedule .= '</li>';
$help_schedule .= '</ul>';
$help_schedule .= '<h4>' . __( 'Schedule Padding', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The amount of padding between the edges of the schedule and the content within the schedule.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Block Padding', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The amount of padding between the edges of the schedule and the content within an office hours or class block.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Column Gap', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The gap between blocks, horizontally and vertically, in the schedule.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Photograph Display', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<ul style="margin-left: 3em;">';
$help_schedule .= '<li style="list-style: disc;">';
$help_schedule .= '<strong>' . __( 'Size', 'faculty-weekly-schedule' ) . '</strong> - ' . __( 'The size of the photograph', 'faculty-weekly-schedule' );
$help_schedule .= '</li>';
$help_schedule .= '<li style="list-style: disc;">';
$help_schedule .= '<strong>' . __( 'Show photograph', 'faculty-weekly-schedule' ) . '</strong> - ' . __( 'Check if the photograph is to be displayed when viewing the schedule', 'faculty-weekly-schedule' );
$help_schedule .= '</li>';
$help_schedule .= '<li style="list-style: disc;">';
$help_schedule .= '<strong>' . __( 'Location', 'faculty-weekly-schedule' ) . '</strong> - ' . __( 'The location in the schedule where the photograph should be displayed', 'faculty-weekly-schedule' );
$help_schedule .= '</li>';
$help_schedule .= '</ul>';
$help_schedule .= '<h4>' . __( 'Title Background Color', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The background color for the name and title headings. If the background color has been set in the <em>Options</em> settings tab, then that background color is defaulted and can be overridden for the schedule. If the background color is not entered, then the background color of the active theme is used.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Title Text Color', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The text color for the name and title headings. If the text color has been set in the <em>Options</em> settings tab, then that text color is defaulted and can be overridden for the schedule. If the text color is not entered, then the text color of the active theme is used.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Schedule Background Color', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The background color for the schedule. If the background color has been set in the <em>Options</em> settings tab, then that background color is defaulted and can be overridden for the schedule. If the background color is not entered, then the background color of the active theme is used.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Schedule Text Color', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The text color for the schedule. If the text color has been set in the <em>Options</em> settings tab, then that text color is defaulted and can be overridden for schedule. If the text color is not entered, then the text color of the active theme is used.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Alignment', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The alignment of the entire schedule. Note that alignment support is required in the theme being used.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Schedule Date and Time Format', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The date and time format of the schedule title. If ', 'faculty-weekly-schedule' ) . ' <em>' . __( 'Site Settings', 'faculty-weekly-schedule' ) . '</em> ' . __( ' is selected, the settings per the ', 'faculty-weekly-schedule' ) . '<a href="/wp-admin/options-general.php">' . __( 'Settings', 'faculty-weekly-schedule' ) . ' &rarr; ' . __( 'General', 'faculty-weekly-schedule' ) . '</a> ' . __( 'are used.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Block Date and Time Format', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The date and time format of the office hours and class block content. If ', 'faculty-weekly-schedule' ) . ' <em>' . __( 'Site Settings', 'faculty-weekly-schedule' ) . '</em> ' . __( ' is selected, the settings per the ', 'faculty-weekly-schedule' ) . '<a href="/wp-admin/options-general.php">' . __( 'Settings', 'faculty-weekly-schedule' ) . ' &rarr; ' . __( 'General', 'faculty-weekly-schedule' ) . '</a> ' . __( 'are used.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';

// Heading Options.
$help_schedule .= '<h3 id="headings">' . __( 'Heading Options', 'faculty-weekly-schedule' ) . '</h3>';
$help_schedule .= '<p>' . __( 'The', 'faculty-weekly-schedule' ) . ' <a href ="' . site_url() . '/wp-admin/edit.php?post_type=fws-schedule&page=faculty_weekly_schedule_settings#fws_headings">' . __( 'Heading Options', 'faculty-weekly-schedule' ) . '</a> ' . __( 'tab allows setting the default values relating to headings whenever a new schedule is added.', 'faculty-weekly-schedule' ) . '.</p>';
$help_schedule .= '<p><img src="' . esc_url( plugins_url( 'schedule/heading-options.jpeg', __FILE__ ) ) . '" alt="' . __( 'Heading Options', 'faculty-weekly-schedule' ) . '" /></p>';
$help_schedule .= '<h4>' . __( 'Heading Options', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<ul style="margin-left: 3em;">';
$help_schedule .= '<li style="list-style: disc;">';
$help_schedule .= '<strong>' . __( 'Show Schedule Heading', 'faculty-weekly-schedule' ) . '</strong> - ' . __( 'Determines if the schedule heading with dates (optionally times) are displayed', 'faculty-weekly-schedule' );
$help_schedule .= '</li>';
$help_schedule .= '<li style="list-style: disc;">';
$help_schedule .= '<strong>' . __( 'Show Classes Heading', 'faculty-weekly-schedule' ) . '</strong> - ' . __( 'Determines if the classes heading is displayed', 'faculty-weekly-schedule' );
$help_schedule .= '</li>';
$help_schedule .= '<li style="list-style: disc;">';
$help_schedule .= '<strong>' . __( 'Show Online Classes Heading', 'faculty-weekly-schedule' ) . '</strong> - ' . __( 'Determines if the online classes heading is displayed', 'faculty-weekly-schedule' );
$help_schedule .= '</li>';
$help_schedule .= '<li style="list-style: disc;">';
$help_schedule .= '<strong>' . __( 'Include Schedule Times', 'faculty-weekly-schedule' ) . '</strong> - ' . __( 'Determines if schedule start and end times are included in the schedule heading', 'faculty-weekly-schedule' );
$help_schedule .= '</li>';
$help_schedule .= '</ul>';
$help_schedule .= '<h4>' . __( 'Heading Text', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<ul style="margin-left: 3em;">';
$help_schedule .= '<li style="list-style: disc;">';
$help_schedule .= '<strong>' . __( 'Schedule Heading', 'faculty-weekly-schedule' ) . '</strong> - ' . __( 'The text before the dates in the schedule heading', 'faculty-weekly-schedule' );
$help_schedule .= '</li>';
$help_schedule .= '<li style="list-style: disc;">';
$help_schedule .= '<strong>' . __( 'Classes Heading', 'faculty-weekly-schedule' ) . '</strong> - ' . __( 'The text for the heading before office hours and classes blocks', 'faculty-weekly-schedule' );
$help_schedule .= '</li>';
$help_schedule .= '<li style="list-style: disc;">';
$help_schedule .= '<strong>' . __( 'Online Classes Heading', 'faculty-weekly-schedule' ) . '</strong> - ' . __( 'The text for the heading before online classes blocks', 'faculty-weekly-schedule' );
$help_schedule .= '</li>';
$help_schedule .= '</ul>';
$help_schedule .= '<h4>' . __( 'Schedule Heading Colors', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The background and text colors for the schedule heading. If the background and text colors have been set in the <em>Options</em> settings tab, then those background and text colors are defaulted and can be overridden for the schedule. If the background and text colors are not entered, then the background and text colors of the active theme is used.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Classes and Office Hours Heading Colors', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The background and text colors for the classes and office hours heading. If the background and text colors have been set in the <em>Options</em> settings tab, then those background and text colors are defaulted and can be overridden for the schedule. If the background and text colors are not entered, then the background and text colors of the active theme is used.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Online Classes Heading Colors', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The background and text colors for the online classes heading. If the background and text colors have been set in the <em>Options</em> settings tab, then those background and text colors are defaulted and can be overridden for the schedule. If the background and text colors are not entered, then the background and text colors of the active theme is used.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Day of Week Heading Colors', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The background and text colors for the day of week heading. If the background and text colors have been set in the <em>Options</em> settings tab, then those background and text colors are defaulted and can be overridden for the schedule. If the background and text colors are not entered, then the background and text colors of the active theme is used.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';

// Schedule Messages.
$help_schedule .= '<h3 id="messages">' . __( 'Schedule Messages', 'faculty-weekly-schedule' ) . '</h3>';
$help_schedule .= '<p>' . __( 'The', 'faculty-weekly-schedule' ) . ' <a href ="' . site_url() . '/wp-admin/edit.php?post_type=fws-schedule&page=faculty_weekly_schedule_settings#fws_messages">' . __( 'Messages Settings', 'faculty-weekly-schedule' ) . '</a> ' . __( 'tab allows setting the default values relating to messages whenever a new schedule is added.', 'faculty-weekly-schedule' ) . '.</p>';
$help_schedule .= '<p><img src="' . esc_url( plugins_url( 'schedule/schedule-messages.jpeg', __FILE__ ) ) . '" alt="' . __( 'Messages Settings', 'faculty-weekly-schedule' ) . '" /></p>';
$help_schedule .= '<h4>' . __( 'Show Before Message', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'Determines whether the before message should be displayed before the schedule.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Before Message Alignment', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'Determines how the before message should be aligned within the schedule.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Before Message', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The before message displayed after the name, title and schedule heading but before the schedule. The <strong>Show Before Message</strong> option must be <strong>Yes</strong> for the after message to display.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'Show After Message', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'Determines whether the after message should be displayed after the schedule.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'After Message Alignment', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'Determines how the after message should be aligned within the schedule.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
$help_schedule .= '<h4>' . __( 'After Message', 'faculty-weekly-schedule' ) . '</h4>';
$help_schedule .= '<p>';
$help_schedule .= __( 'The after message displayed after the schedule. The <strong>Show After Message</strong> option must be <strong>Yes</strong> for the after message to display.', 'faculty-weekly-schedule' );
$help_schedule .= '</p>';
